name: Deploy Jekyll site # Updated workflow file
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true  # Caches gems automatically
      - name: Update Bundler
        run: |
          gem install bundler
          bundle update --bundler
      - name: Fix URI gem version
        run: |
          echo "gem 'uri', '0.10.1'" >> Gemfile
          bundle update
      - name: Install dependencies
        run: |
          bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build --trace
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
