name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Ruby
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true

    # Step 3: Debug Ruby, Bundler, and Jekyll versions
    - name: Check Installed Versions
      run: |
        ruby -v
        bundler -v
        gem list jekyll

    # Step 4: Install Jekyll and Bundler
    - name: Install Jekyll & Bundler
      run: |
        gem install jekyll bundler
        bundle install --jobs 4 --retry 3

    # Step 5: Install additional dependencies
    - name: Install deps
      run: |
        npm install -g mermaid.cli

    # Step 6: Setup deployment options
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT

    # Step 7: Debug bin/deploy script
    - name: Check Deploy Script
      run: |
        ls -l bin/deploy
        cat bin/deploy

    # Step 8: Ensure Deploy Script is Executable
    - name: Make Deploy Script Executable
      run: chmod +x bin/deploy

    # Step 9: Build Jekyll site
    - name: Build Jekyll site
      run: bundle exec jekyll build --trace

    # Step 10: Deploy website
    - name: Deploy website
      run: |
        yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} \
        --src ${{ steps.setup.outputs.SRC_BRANCH }} \
        --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }} 
